name: renweather
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_dio_interceptor: ^1.2.0
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/animations/
